### ISSUE TITLE
肉鸽/保全/生息演算设置修改，

### ISSUE THREAD

**Issue by Shawnsdaddy** [ArkMowers/arknights-mower#206]
目前是3个 bool type flag。。

准备修改成一个的type

**Comment by ZhaoZuohong** [comment]
配置文件如果采用这样的格式如何：

```yaml
maa:
  path: /home/zhao/Downloads/MAA-v4.14.1-linux-x86_64/
  adb: /usr/bin/adb
  gap: 4
  weekly_plan:
    - medicine: 0
      stage: ['']
      weekday: 周一
  mall:
    blacklist: 碳,家具,加急许可
    buy: 招聘许可,龙门币
  recruit:
    only_4: false
    time: false
  long_jobs:
    rg:
      enable: 0
      sleep_min: 9:30
      sleep_max: 8:30
    sss:
      enable: 0
      sleep_min: 9:30
      sleep_max: 8:30
      type: SSS_多索雷斯在建地块
      copilot_file_location: /home/zhao/Downloads/MAA-v4.14.1-linux-x86_64/resource/copilot/SSS_多索雷斯在建地块.json
      copilot_loop_times: 3

```
