### ISSUE TITLE
高级邮件设置

### ISSUE THREAD

**Issue by ZhaoZuohong** [ArkMowers/arknights-mower#279]
功能列表：

- [ ] 支持任意邮件发信
- [ ] 支持多个收件人
- [ ] 每个收件人可独立设置时区

**Comment by ZhaoZuohong** [comment]
# 设计图

## 简单模式

对简单模式也进行一点调整。

![image](https://github.com/ArkMowers/arknights-mower/assets/34163622/8f77cb1f-0867-4b40-a0a7-f67b13b83409)

## 高级模式

![image](https://github.com/ArkMowers/arknights-mower/assets/34163622/62d36dde-452b-4670-bb0e-9caf321e014e)

**Comment by ZhaoZuohong** [comment]
配置文件里高级邮件设置的格式：

```yaml
advanced_email:
  enable: false
  smtp_server: ''
  port: 465
  encryption: 'ssl'
  authentication: 'normal password'
  account: ''
  password: ''
  to:
    - address: example@example.com
      timezone: 'Asia/Shanghai'
    - address: example@example.com
      timezone: 'Asia/Shanghai'
```
